### ISSUE TITLE
Outofdate

### ISSUE THREAD

**Issue by queenofdamed** [smallo92/FireplaceUtilities#1]
mod has bin broken via Heath and home update. please update would appreciate it

**Comment by Notion615** [comment]
yeah, i can confirm mod is not working with hearth and home update. The config correctly shows hotkeys on the fireplace but nothing happens when you click the button assigned. i have tested local client side and with a decicated server with the mod installed.

**Comment by Cronosus** [comment]
yeah, broken, spam this in console
`[Error  : Unity Log] MissingMethodException: UnityEngine.GameObject[] EffectList.Create(UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.Transform,single)
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)`

**Comment by smallo92** [comment]
As you guys can very clearly see, this hasn't been updated in 13 months and I don't mod this game anymore. People are welcome to submit PRs.

**Comment by rockrevenchy** [comment]
@smallo92 I understand you left valheim modding altho your mods on thunderstore are still listed as functional, if you got any time could you lock or remove them, also thank you for creating it in the first place ;p
